/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;
import br.senai.sp.jandira.dao.EspecialidadeDAO;
import br.senai.sp.jandira.dao.MedicoDAO;
import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.Especialidade;
import br.senai.sp.jandira.model.Medico;
import br.senai.sp.jandira.model.TipoOperacao;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author 22282103
 */
public class MedicoPanel extends javax.swing.JPanel {

    int linha;
    /**
     * Creates new form MedicoPanel
     */
    public MedicoPanel() {
        initComponents();
        criarTabelaMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMedico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ExcluirMedico = new javax.swing.JButton();
        AdicionarMedico = new javax.swing.JButton();
        EditarMedico = new javax.swing.JButton();

        setLayout(null);

        TableMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableMedico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 80, 710, 310);

        jLabel1.setText("Medico");
        add(jLabel1);
        jLabel1.setBounds(10, 40, 280, 40);

        ExcluirMedico.setText("jButton1");
        ExcluirMedico.setActionCommand("AdicionarMedico");
        ExcluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirMedicoActionPerformed(evt);
            }
        });
        add(ExcluirMedico);
        ExcluirMedico.setBounds(430, 470, 80, 50);

        AdicionarMedico.setText("jButton1");
        add(AdicionarMedico);
        AdicionarMedico.setBounds(530, 470, 75, 50);

        EditarMedico.setText("jButton1");
        add(EditarMedico);
        EditarMedico.setBounds(620, 470, 75, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirMedicoActionPerformed
        linha = TableMedico.getSelectedRow();
        
        if (linha != -1) {
            excluir();
        }
        
    }//GEN-LAST:event_ExcluirMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarMedico;
    private javax.swing.JButton EditarMedico;
    private javax.swing.JButton ExcluirMedico;
    private javax.swing.JTable TableMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaMedico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
