/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.PlanoDeSaude;
import br.senai.sp.jandira.model.TipoOperacao;
import br.senai.sp.jandira.ui.DailogPlanosDeSaude;
import br.senai.sp.jandira.ui.PanelPlanosDeSaude;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author 22282099
 */
public class PanelPlanosDeSaude extends javax.swing.JPanel {

    int linha;
    
    /**
     * Creates new form PanelPlanosDeSaude
     */
    public PanelPlanosDeSaude() {
        initComponents();
        criarTabelaPlanosDeSaude();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        scrollTablePlanosDeSaude = new javax.swing.JScrollPane();
        tablePlanosDeSaude = new javax.swing.JTable();
        buttonExcluirPlanoDeSaude = new javax.swing.JButton();
        buttonAlterarPlanoDeSaude = new javax.swing.JButton();
        buttonAdicionarPlanoDeSaude = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(null);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 4, 61));
        jLabel3.setText("Planos de saúde");
        add(jLabel3);
        jLabel3.setBounds(20, 10, 180, 20);

        tablePlanosDeSaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTablePlanosDeSaude.setViewportView(tablePlanosDeSaude);

        add(scrollTablePlanosDeSaude);
        scrollTablePlanosDeSaude.setBounds(20, 40, 905, 240);

        buttonExcluirPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/excluir (1).png"))); // NOI18N
        buttonExcluirPlanoDeSaude.setToolTipText("Excluir plano de saúde selecionado");
        buttonExcluirPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirPlanoDeSaudeActionPerformed(evt);
            }
        });
        add(buttonExcluirPlanoDeSaude);
        buttonExcluirPlanoDeSaude.setBounds(690, 290, 70, 60);

        buttonAlterarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/caneta.png"))); // NOI18N
        buttonAlterarPlanoDeSaude.setToolTipText("Editar plano de saúde selecionado");
        buttonAlterarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarPlanoDeSaudeActionPerformed(evt);
            }
        });
        add(buttonAlterarPlanoDeSaude);
        buttonAlterarPlanoDeSaude.setBounds(770, 290, 70, 60);

        buttonAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/botao-adicionar (1).png"))); // NOI18N
        buttonAdicionarPlanoDeSaude.setToolTipText("Adicionar plano de saúde");
        buttonAdicionarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPlanoDeSaudeActionPerformed(evt);
            }
        });
        add(buttonAdicionarPlanoDeSaude);
        buttonAdicionarPlanoDeSaude.setBounds(850, 290, 70, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAlterarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarPlanoDeSaudeActionPerformed
         linha = tablePlanosDeSaude.getSelectedRow();
        
        if (linha != -1){    
            editar();
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Selecione o Plano de Saúde que deseja alterar", 
                    "Plano de Saúde", 
                    JOptionPane.WARNING_MESSAGE);
            
        }
        
       
    }//GEN-LAST:event_buttonAlterarPlanoDeSaudeActionPerformed

    private void editar(){
    
        PlanoDeSaude planoDeSaude = PlanoDeSaudeDAO.getPlanoDeSaude(returnCodigo());
        
         DailogPlanosDeSaude dailogPlanosDeSaude = new DailogPlanosDeSaude(
                null, 
                true, 
                TipoOperacao.ALTERAR,
                planoDeSaude);
        
        dailogPlanosDeSaude.setVisible(true);
        
        criarTabelaPlanosDeSaude();
    }
    
    private void buttonExcluirPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirPlanoDeSaudeActionPerformed
        
        //Obtemos o índice de linhas selecionadas na tabela
         linha = tablePlanosDeSaude.getSelectedRow();     
        
        //Verficamos se a linha é diferente de -1
        //Caso for -1, significa que o usuário não selecionou nada
        if (linha != -1){
            excluir(linha);           
        }else{
            JOptionPane.showMessageDialog(this,
                    "Você não selecionou nenhuma linha",
                    "Exclusão de plano",
                    JOptionPane.ERROR_MESSAGE);
        }    
    
    
    }//GEN-LAST:event_buttonExcluirPlanoDeSaudeActionPerformed
       
        public void excluir(int a){
            
            int resposta = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir esse Plano de Saúde?",
                "Exclusão Plano de Saúde",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            
            System.out.println(resposta);           
           
            if(resposta == 0){  
                
                PlanoDeSaudeDAO.excluir(returnCodigo());
                criarTabelaPlanosDeSaude();
         }
        }   
    
        private Integer returnCodigo(){
            String codigoString =  tablePlanosDeSaude.getValueAt(linha, 0).toString();
            return Integer.valueOf(codigoString);
        }
        
    
    private void buttonAdicionarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPlanoDeSaudeActionPerformed
        
        DailogPlanosDeSaude dialogPlanosDeSaude = new DailogPlanosDeSaude(
                null, 
                true, 
                TipoOperacao.ADICIONAR,
                null);
        
        dialogPlanosDeSaude.setVisible(true);      
        criarTabelaPlanosDeSaude();
    
    }//GEN-LAST:event_buttonAdicionarPlanoDeSaudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPlanoDeSaude;
    private javax.swing.JButton buttonAlterarPlanoDeSaude;
    private javax.swing.JButton buttonExcluirPlanoDeSaude;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrollTablePlanosDeSaude;
    private javax.swing.JTable tablePlanosDeSaude;
    // End of variables declaration//GEN-END:variables
   
    private void criarTabelaPlanosDeSaude() {

        tablePlanosDeSaude.setModel(PlanoDeSaudeDAO.getTableModel());

        // Desativar o redimensionamento da JTable
        tablePlanosDeSaude.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Definir a largura de cada coluna
        tablePlanosDeSaude.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablePlanosDeSaude.getColumnModel().getColumn(1).setPreferredWidth(300);
        tablePlanosDeSaude.getColumnModel().getColumn(2).setPreferredWidth(300);

        // Impedir/bloquear a movimentação das colunas
        tablePlanosDeSaude.getTableHeader().setReorderingAllowed(false);

        // Bloquear edição das células
        tablePlanosDeSaude.setDefaultEditor(Object.class, null);

    }
}
